image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt || pip install django dj-database-url typing_extensions
      pip freeze > requirements.txt
  - command: |
      /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
      . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
      source venv/bin/activate
      python3 manage.py runserver

vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
