image: gitpod/workspace-full:latest

tasks:
  - name: Setup and Run Django
    init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    command: |
      source venv/bin/activate
      python3 manage.py runserver 0.0.0.0:8000

ports:
  - port: 8000
    onOpen: open-preview
