# Generated by Django 5.1.4 on 2025-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_created_at_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_category',
            field=models.CharField(blank=True, choices=[('logo_designs', 'Logo Designs'), ('website_design', 'Website Design'), ('stationary_design', 'Stationary Design'), ('business_cards', 'Business Cards'), ('social_media_graphics', 'Social Media Graphics'), ('flyer_design', 'Flyer Design'), ('packaging_design', 'Packaging Design'), ('custom_prints', 'Custom Prints')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
    ]
