# Generated by Django 5.1.4 on 2025-05-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename__id_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_options/'),
        ),
    ]
