# Generated by Django 5.1.4 on 2025-05-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productoption_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
